# Generated by Django 2.2.1 on 2019-05-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Стриж', max_length=32)),
                ('title', models.CharField(default='Я забыла написать название поста', max_length=64)),
                ('content', models.CharField(max_length=1500)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
